name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies if requirements.txt exists
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "No requirements.txt found, skipping dependencies installation."
        fi

    - name: Analyse the code with pylint if *.py files exist
      run: |
        py_files=$(git ls-files '*.py')
        if [ -z "$py_files" ]; then
          echo "No Python files found, skipping pylint analysis."
        else
          pylint --fail-under 9.0 **/*.py
        fi

